name: Daily Prediction Update

on:
  schedule:
    - cron: "0 3 * * 1-5"   # 08:30 IST (Mon–Fri)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install yfinance pandas numpy scikit-learn

      - name: Run prediction script
        run: |
          python app.py

      - name: Commit updated log
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add daily_portfolio_log.csv
          git commit -m "Daily prediction update" || echo "No changes"
          git push
