name: Weekly Stock Prediction (Gradient Boosting)

on:
  schedule:
    - cron: "30 3 * * 1"   # Monday 09:00 IST
  workflow_dispatch:

jobs:
  run-weekly:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install yfinance pandas numpy scikit-learn

      - name: Run weekly prediction job
        run: |
          python weekly_job.py

      - name: Commit results
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add weekly_predictions_log.csv
          git commit -m "Weekly prediction update" || echo "No changes"
          git push
